### ISSUE TITLE
I cant see the states in states call

### ISSUE THREAD

**Issue by wasiqaftab** [nnjeim/world#11]
HI 

i am trying to do this call 

`$action =  World::states([
                        'filters' => [
                            'country_id' => 168
                         ]
                    ]);`

it's not given me the states for that country just giving me cities but if i change the filter to ios2 it will give me data. but problem is that in database i am storing country id any idea why its doing like that

**Comment by nnjeim** [comment]
Hi Wasiq,
I run the same query on my end and i am attaching the result here below.
I acknowledge having a bug in states that was fixed in release 1.1.1
Try to upgrade to the latest version and clear your cache.
Please let me know if this will work.

![Screenshot 2022-01-27 at 03 44 13](https://user-images.githubusercontent.com/78922079/151276658-c9e91e4f-f87a-4d0d-b8e1-fd05466e0b14.jpg)

**Comment by wasiqaftab** [comment]
@nnjeim thanks its fixed
