### ISSUE TITLE
Too long to execute on Laravel Vapor

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [nnjeim/world#74]
Hi, The time to seed the db is too long for laravel vapor
Maybe split seed DB with jobs ?
I do not know the exact way to achieve it, but it is not possible on small architecture to seed the db on laravel vapor
Best regards

**Comment by nnjeim** [comment]
Hi @Kixell-NicolasJardillier I have no experience with Vapor. However you might consider 2 options:
- set the php memory to -1 in php.ini (max available mem)
- seed locally and import the sqldump on vapor.

i am pretty sure that the limited performance is due to the available resources on Vapor when seeding.

cheers,

**Comment by Kixell-NicolasJardillier** [comment]
Hi @nnjeim yes it works by seeding locally and import
The limit comes from the time to execute the seed on lambda AWS functions not vapor directly

best regards
